### ISSUE TITLE
Improving Performance

### ISSUE THREAD

**Issue by byjlw** [anordin95/run-llama-locally#2]
Hey, love your minimal dependency approach. 

Check out [torchchat](https://github.com/pytorch/torchchat
), PyTorch's LLM inference solution. Currently you can get 20+ tokens / second on an M1 CPU only and significantly more using --device mps.

If you want to keep your project as thin as possible you can borrow just the code you want to keep your project lightweight and still get good performance.

**Comment by anordin95** [comment]
Hey hey!

Ah, that sounds neat! And is certainly better performance. I'll add it to the short-list of alternative ways to invoke Meta's LLMs in the README. I'm not familiar with `torchchat`, but I'm not sure it would do what I'd like here. My goal here was to get my hands on a `torch.nn.Module` object that I could directly interrogate and play around with in a REPL. A way to look at model weights & their sizes, the activations in different layers, probability distributions in the output, etc. 

Performance isn't really a concern (so long as it's not totally abysmal) and I think using torchchat would hinder snooping around the model.
